### ISSUE TITLE
Training takes a lot of time

### ISSUE THREAD

**Issue by tbozinis** [Cadene/block.bootstrap.pytorch#7]
I followed the instantiations on [README](https://github.com/Cadene/block.bootstrap.pytorch/blob/master/README.md) _(I installed everything and took the features from here: https://github.com/Cadene/murel.bootstrap.pytorch/issues/1)_

Then I run this: `python -m bootstrap.run -o block/options/vqa2/block.yaml` and training started.

The problem is that although I can see with `nvidia-smi` that the model is loaded on the GPU I only see some spikes on the GPU utilization _(form 0 to 30% for 1 second)_ **and** one epoch was running for at least 22mins _(and processed 1/3 of the training set)_.

Is this normal?

> I remember that I had the same _problem_ with [vqa.pytorch](https://github.com/Cadene/vqa.pytorch) and I resolved it by adding `cuda(async=True)` 
 on [`input_visual   = Variable(sample['visual'])`](https://github.com/Cadene/vqa.pytorch/blob/master/vqa/lib/engine.py#L18).

**Comment by Cadene** [comment]
@tbozinis Sorry for the late answer

> I remember that I had the same problem with vqa.pytorch and I resolved it by adding cuda(async=True)

The cuda transfer is already done asynchronously [[source](https://github.com/Cadene/bootstrap.pytorch/blob/master/bootstrap/datasets/transforms.py#L173)].

> The problem is that although I can see with nvidia-smi that the model is loaded on the GPU I only see some spikes on the GPU utilization (form 0 to 30% for 1 second) and one epoch was running for at least 22mins (and processed 1/3 of the training set). Is this normal?

Not it's not normal. You can verify it by looking at the logs (`logs.txt`) from the [pretrained models](https://github.com/Cadene/block.bootstrap.pytorch#vqa2).

The slow loading time is probably due to a slow reading from your disk.
You should consider using a dedicated SSD with a (really) fast i/o.
You can verify this with `atop` ([doc](https://linux.die.net/man/1/atop)). If you see something red on atop, it means that there is a problem with your disk.

**Comment by tbozinis** [comment]
Yes, you where right about the SSDs... Now it's much faster.
